"""Drop session and add owner_id

Revision ID: 12a6875ba3b6
Revises: 001
Create Date: 2026-07-21 22:18:03.243521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12a6875ba3b6'
down_revision: Union[str, Sequence[str], None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Data migration: delete orphaned rows and their storage files
    import shutil
    import os
    
    conn = op.get_bind()
    # Get all file storage paths before deletion
    files = conn.execute(sa.text("SELECT storage_path FROM files")).fetchall()
    for row in files:
        if row[0] and os.path.exists(row[0]):
            shutil.rmtree(row[0], ignore_errors=True)
            
    # Explicitly delete child records in order
    conn.execute(sa.text("DELETE FROM charts"))
    conn.execute(sa.text("DELETE FROM prompts"))
    conn.execute(sa.text("DELETE FROM files"))

    with op.batch_alter_table('charts', schema=None) as batch_op:
        batch_op.alter_column('chart_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.String(length=36), nullable=False))
        batch_op.create_index(batch_op.f('ix_files_owner_id'), ['owner_id'], unique=False)
        batch_op.drop_index('ix_files_session_id')
        batch_op.drop_column('session_id')

    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))

    op.drop_table('sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompts_file_id'))
        batch_op.alter_column('status',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.CHAR(length=36), nullable=False))
        batch_op.create_foreign_key(None, 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_files_owner_id'))
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('charts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_charts_prompt_id'))
        batch_op.alter_column('chart_type',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)

    op.create_table('sessions',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_active_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
