"""Add preview_rows column

Revision ID: 795420f44a86
Revises: 12a6875ba3b6
Create Date: 2026-07-22 09:39:50.969467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import backend.core.database


# revision identifiers, used by Alembic.
revision: str = '795420f44a86'
down_revision: Union[str, Sequence[str], None] = '12a6875ba3b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charts', schema=None) as batch_op:
        pass

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preview_rows', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('dashboard_config', sa.JSON(), nullable=True))

    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('explanation', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.alter_column('file_id',
               existing_type=backend.core.database.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=backend.core.database.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
        batch_op.drop_column('explanation')

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=backend.core.database.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
        batch_op.drop_column('dashboard_config')
        batch_op.drop_column('preview_rows')

    with op.batch_alter_table('charts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_charts_prompt_id'))
        batch_op.create_index(batch_op.f('ix_charts_prompt_id'), ['prompt_id'], unique=False)
        batch_op.alter_column('prompt_id',
               existing_type=backend.core.database.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=backend.core.database.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###
